/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "movecraft-parent"
include(":movecraft-v1_21_3")
include(":movecraft-api")
include(":movecraft-datapack")
include(":movecraft")
project(":movecraft-v1_21_3").projectDir = file("v1_21_3")
project(":movecraft-api").projectDir = file("api")
project(":movecraft-datapack").projectDir = file("datapack")
project(":movecraft").projectDir = file("Movecraft")
